# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b54b1045757b15cf059306a97d441a0393b2a0adf64536ad5c8124760c2359b9648a39f82c272ff2f12811eee01656f0c96aeca67f76f4b811903833a25bcbaf

test:
  secret_key_base: 2338e6261335030959f69b3fdc308620b525613cf33e30e653fafe0bb9ed2dac44319ad12dbc4aa203b8178a01251817ed5ba33a8a560e8774927e20b754bae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 0b786b8ae60281251229962361756a94a4017fd55b76dbca0f5083fc3bc3ad10e31ad7a2ea35fde8d81eac7530185cb11176b143f5822eb640a93cad792443c2
